# Generated by Django 5.1 on 2024-08-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_passenger'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], help_text='Rating out of 5')),
                ('comment', models.TextField(blank=True, help_text='Optional comment for the review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_object_id', models.PositiveIntegerField()),
                ('reviewee_object_id', models.PositiveIntegerField()),
                ('reviewee_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee_reviews', to='contenttypes.contenttype')),
                ('reviewer_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_reviews', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('from_location', models.CharField(db_index=True, max_length=100)),
                ('to_location', models.CharField(db_index=True, max_length=100)),
                ('is_reverese_trip', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='organization.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('jeep', 'Jeep'), ('hilux', 'Hilux'), ('bike', 'Bike'), ('bus', 'Bus'), ('car', 'Car')], db_index=True, max_length=10)),
                ('company_made', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='black', max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=0)),
                ('license_plate_number', models.CharField(max_length=10, unique=True)),
                ('insurance_expiry_date', models.DateField()),
                ('fitness_certificate_expiry_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images')),
                ('available_seat', models.PositiveIntegerField(default=0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='vehicle_driver', to='authentication.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='vehicle_organization', to='authentication.organization')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='organization.vehicle'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_occupied', models.BooleanField(default=False)),
                ('reserved_for_driver', models.BooleanField(default=False)),
                ('reserved_for_conductor', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='organization.vehicle')),
            ],
        ),
    ]
