# Generated by Django 5.1 on 2024-08-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_trip_passenger_count_trip_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
