# Generated by Django 5.1 on 2024-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_trip_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='from_location',
            field=models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('chitwan', 'Chitwan'), ('lumbini', 'Lumbini'), ('janakpur', 'Janakpur'), ('biratnagar', 'Biratnagar'), ('birgunj', 'Birgunj'), ('dharan', 'Dharan'), ('butwal', 'Butwal'), ('hetauda', 'Hetauda'), ('nepalgunj', 'Nepalgunj'), ('dhangadhi', 'Dhangadhi'), ('bharatpur', 'Bharatpur'), ('itahari', 'Itahari'), ('gaur', 'Gaur'), ('tansen', 'Tansen'), ('jomsom', 'Jomsom'), ('namche_bazaar', 'Namche Bazaar'), ('manang', 'Manang'), ('lukla', 'Lukla')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_location',
            field=models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('chitwan', 'Chitwan'), ('lumbini', 'Lumbini'), ('janakpur', 'Janakpur'), ('biratnagar', 'Biratnagar'), ('birgunj', 'Birgunj'), ('dharan', 'Dharan'), ('butwal', 'Butwal'), ('hetauda', 'Hetauda'), ('nepalgunj', 'Nepalgunj'), ('dhangadhi', 'Dhangadhi'), ('bharatpur', 'Bharatpur'), ('itahari', 'Itahari'), ('gaur', 'Gaur'), ('tansen', 'Tansen'), ('jomsom', 'Jomsom'), ('namche_bazaar', 'Namche Bazaar'), ('manang', 'Manang'), ('lukla', 'Lukla')], db_index=True, max_length=100),
        ),
    ]
