trip_choices = [
    ('kathmandu', 'Kathmandu'),
    ('pokhara', 'Pokhara'),
    ('chitwan', 'Chitwan'),
    ('lumbini', 'Lumbini'),
    ('janakpur', 'Janakpur'),
    ('biratnagar', 'Biratnagar'),
    ('birgunj', 'Birgunj'),
    ('dharan', 'Dharan'),
    ('butwal', 'Butwal'),
    ('hetauda', 'Hetauda'),
    ('nepalgunj', 'Nepalgunj'),
    ('dhangadhi', 'Dhangadhi'),
    ('bharatpur', 'Bharatpur'),
    ('itahari', 'Itahari'),
    ('gaur', 'Gaur'),
    ('tansen', 'Tansen'),
    ('jomsom', 'Jomsom'),
    ('namche_bazaar', 'Namche Bazaar'),
    ('manang', 'Manang'),
    ('lukla', 'Lukla'),
]
