# Generated by Django 5.1 on 2024-09-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('not_resolved', 'Not Resolved')], default='not_resolved', max_length=12),
        ),
    ]
