# Generated by Django 5.1 on 2024-09-20 03:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='support_requests'),
        ),
    ]
