# Generated by Django 5.1 on 2024-09-20 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supportrequest_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('not_resolved', 'Not Resolved'), ('pending', 'Pending')], default='not_resolved', max_length=12),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('acknowledgment', 'Acknowledgment'), ('improvement', 'Improvement')], max_length=20)),
                ('comments', models.TextField()),
                ('track_options', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
