# Generated by Django 5.1 on 2024-08-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
