# Generated by Django 5.1 on 2024-08-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_payment_is_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
