# Generated by Django 5.1 on 2024-08-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_passenger'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=200, unique=True)),
                ('num_passengers', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.passenger')),
                ('seats', models.ManyToManyField(related_name='bookings', to='organization.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=200, unique=True)),
                ('ticket_file', models.FileField(max_length=200, upload_to='tickets/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
