# Generated by Django 5.1 on 2024-08-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='organization.seat'),
        ),
    ]
