# Generated by Django 5.1 on 2024-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
