# Generated by Django 5.1 on 2024-08-27 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 27, 6, 48, 6, 507687, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
