# Generated by Django 5.1 on 2024-08-27 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_trip_datetime'),
        ('organization', '0003_trip_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(default=django.utils.timezone.now)),
                ('num_passengers_on_that_day', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bookings', models.ManyToManyField(blank=True, related_name='daily_earnings', to='booking.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_earnings', to='organization.trip')),
            ],
        ),
    ]
