# Generated by Django 5.1 on 2024-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_dailyearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip_datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
