# Generated by Django 5.1 on 2024-08-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.profile')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('preferred_language', models.CharField(blank=True, choices=[('en', 'English'), ('ne', 'Nepali')], max_length=20)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
            bases=('authentication.profile',),
        ),
    ]
