# Generated by Django 5.1 on 2024-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_driver_no_of_trips_organization_no_of_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
