# Generated by Django 5.1 on 2024-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
